import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Static page",
  description: "Generated by create next app",
};

const StaticRenderingPage = () => {
  return (
    <div>
      <h1>StaticRenderingPage</h1>
      <p>{new Date().toTimeString()}</p>
    </div>
  );
};

export default StaticRenderingPage;
